### ISSUE TITLE
the result is not good, please tell me why

### ISSUE THREAD

**Issue by yingma111** [Gofinge/PyCannyLine#1]
I modify demo as follow:
```
if __name__ == '__main__':
    detector = MetaLine()
    image_path = "image\\6-2-1.1.bmp.resize.png"
    src = cv2.imread(image_path)
    image = cv2.cvtColor(src, cv2.COLOR_BGR2GRAY)
    image = cv2.pyrDown(image)
    image = cv2.pyrDown(image)
    image = cv2.pyrDown(image)

    results = detector.meta_line_detection(image, 1, 1)
    for start_c, start_r, end_c, end_r, _ in results:
        cv2.line(src, (int(start_c), int(start_r)), (int(end_c), int(end_r)), (255, 255, 0), thickness=1,
                 lineType=cv2.LINE_AA)
    cv2.imwrite("output.png", src)
```
"output.png" as follow:
![output](https://user-images.githubusercontent.com/53547240/108955152-a503b900-76a8-11eb-8700-4acd1b1e59d2.png)
I don't think this result is good, I don't know why.

**Comment by Gofinge** [comment]
there is no need to "pydown" for the sample image since it is in low resolution, it is for full resolution image. I will update the demo main. Thanks!

**Comment by Gofinge** [comment]
![image](https://user-images.githubusercontent.com/39218229/108958376-da5ed580-76ad-11eb-8d8a-f6b3c7de1d67.png)
