### ISSUE TITLE
test this algorithm by my images, but results are wrong

### ISSUE THREAD

**Issue by yingma111** [Gofinge/PyCannyLine#2]
I have many images, and I test them by this PyCannyLine algorithm, the reuslts are not good.
this is my demo code:
```
if __name__ == '__main__':
    import glob
    detector = MetaLine()
    filenames = glob.glob("image\\images\\*.png")
    # image_path = "image\\images\\1.png"

    for num, image_path in enumerate(filenames):
        src = cv2.imread(image_path)
        image = cv2.cvtColor(src, cv2.COLOR_BGR2GRAY)
        image = cv2.pyrDown(image)
        image = cv2.pyrDown(image)
        image = cv2.pyrDown(image)

        results = detector.meta_line_detection(image, 1, 1)
        for start_c, start_r, end_c, end_r, _ in results:
            cv2.line(src, (int(start_c), int(start_r)), (int(end_c), int(end_r)), (255, 255, 0), thickness=1,
                     lineType=cv2.LINE_AA)
        cv2.imwrite("image\\output\\output" + str(num) + ".png", src)
```
My source images as follow:
[images.zip](https://github.com/Gofinge/PyCannyLine/files/6034374/images.zip)

As github limit, I can't load all output images.All output images are similar, one of output images is as follow:
![output0](https://user-images.githubusercontent.com/53547240/108968615-f79aa080-76bb-11eb-8f96-ad0eda9b999d.png)

Can you help me test by these images?

**Comment by Gofinge** [comment]
![Uploading image.png…]()

**Comment by Gofinge** [comment]
![image](https://user-images.githubusercontent.com/39218229/108971064-0fbeef80-76bd-11eb-9383-8455ff661785.png)

**Comment by Gofinge** [comment]
src was the original size image, but the lines detected were based on the down-sampled image. You should draw the lines on the down-sampled image, or upsample the lines.

btw: in your case, there is no necessary to "pyrDown" three times, you can conduct an experience.

**Comment by Gofinge** [comment]
![image](https://user-images.githubusercontent.com/39218229/108972529-60831800-76be-11eb-9a95-549190c43221.png)

**Comment by Gofinge** [comment]
Here are the results: 
[output.zip](https://github.com/Gofinge/PyCannyLine/files/6034564/output.zip)

**Comment by yingma111** [comment]
Can you give me your demo code?

**Comment by Gofinge** [comment]
https://github.com/Gofinge/PyCannyLine/blob/d5b452e117d8945ba0a716202621dee15b163d58/cannyline.py#L1047

**Comment by yingma111** [comment]
thanks
